POST http://localhost:8080/order
Content-Type: application/json

{
  "products": [
    {
      "id": "apple-2000",
      "quantity": 5
    },
    {
      "id": "macbook-10000",
      "quantity": 5
    }
  ]
}

