server:
  port: 8080

springdoc:
  swagger-ui:
    path: /

spring:
  application:
    name: order-service
  couchbase:
    cluster:
      timeout: 15
    bucket:
      timeout: 15
      name: Order
      user: Administrator
      password: password
    host: couchbase_okur

client:
  product-service:
    base-url: http://product-service:2222
    connect-timeout: 5000
    read-timeout: 10000
